server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: goodsop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.30:65432/mydb_test
    username: post
    password: admin@2025
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.goodsop.**.entity
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

knife4j:
  enable: true
  production: false
  
logging:
  level:
    root: info
    com.goodsop: debug
  file:
    name: logs/goodsop-test.log

# 文件模块配置
goodsop:
  file:
    storage:
      path: /home/file/
      enable-decrypt: true
      enable-decompress: true
      aes-key: 1234567890abcdef1234567890abcdef
      server-host: dev.goodsop.cn
      server-port: 80
      context-path: /api
    upload:
      max-size: 100MB
    cleanup:
      enabled: true
      cron: "0 0 1 * * ?"  # 每天凌晨1点执行
      temp-file-max-age: 24  # 临时文件最大保留时间（小时） 