server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: goodsop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.30:65432/mydb
    username: post
    password: admin@2025
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.goodsop.**.entity
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

knife4j:
  enable: true
  openapi:
    title: Goodsop API文档
    description: Goodsop REST API接口文档
    email: admin@goodsop.com
    version: 1.0.0
    license: Apache 2.0
    license-url: https://goodsop.com
    terms-of-service-url: https://goodsop.com

logging:
  level:
    root: info
    com.goodsop: debug
  file:
    name: logs/goodsop-dev.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30 