version: '3.8'

services:
  # 专用控制器节点
  kafka1:
    image: apache/kafka:3.7.0
    container_name: kafka1
    hostname: kafka1
    networks:
      - kafka-kraft-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller"  # 关键修改
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:19093"  # 唯一控制器
      KAFKA_LISTENERS: "CONTROLLER://0.0.0.0:19093"  # 仅需控制器监听
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"  # 控制器监听器名称
      CLUSTER_ID: "zt8eKmYSTnO4oWv8C0eDcA"
      KAFKA_LOG_DIRS: "/kafka/data"
      KAFKA_METADATA_VERSION: 3.7-IV0  # 强制元数据版本
    volumes:
      - ./node1/data:/kafka/data
    ports:
      - "19093:19093"  # 暴露控制器端口

  # Broker节点配置
  kafka2:
    image: apache/kafka:3.7.0
    container_name: kafka2
    hostname: kafka2
    networks:
      - kafka-kraft-net
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker"  # 仅Broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:19093"  # 指向专用控制器
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"  # 只需要PLAINTEXT监听器
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "BROKER_CONTROLLER"  # 必需但与LISTENERS不同名
      CLUSTER_ID: "zt8eKmYSTnO4oWv8C0eDcA"
      KAFKA_LOG_DIRS: "/kafka/data"
      KAFKA_METADATA_VERSION: 3.7-IV0
    volumes:
      - ./node2/data:/kafka/data
    ports:
      - "29092:9092"

  kafka3:
    image: apache/kafka:3.7.0
    container_name: kafka3
    hostname: kafka3
    networks:
      - kafka-kraft-net
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:19093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"  # 只需要PLAINTEXT监听器
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "BROKER_CONTROLLER"  # 必需但与LISTENERS不同名
      CLUSTER_ID: "zt8eKmYSTnO4oWv8C0eDcA"
      KAFKA_LOG_DIRS: "/kafka/data"
      KAFKA_METADATA_VERSION: 3.7-IV0
    volumes:
      - ./node3/data:/kafka/data
    ports:
      - "39092:9092"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "38080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: KafkaCluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka2:9092,kafka3:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: kafka-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
      # 中文界面设置 - 更新的配置方式
      SPRING_APPLICATION_JSON: '{"server":{"servlet":{"context-path":"/"},"lang":"zh-CN"}}'
      SERVER_SERVLET_CONTEXT_PATH: "/"
      SPRING_PROFILES_ACTIVE: "chinese,local"
      # 设置浏览器语言检测为首选
      SERVER_FORWARD_HEADERS_STRATEGY: NATIVE
    networks:
      - kafka-kraft-net
    depends_on:
      - kafka1
      - kafka2
      - kafka3

networks:
  kafka-kraft-net:
    driver: bridge
    attachable: true

