networks:
  kafka-net:
    driver: bridge

services:
  kafka1:
    image: bitnami/kafka:3.7.0
    container_name: kafka1
    hostname: kafka1
    ports:
      - "39092:29092"  # External client port for kafka1
    volumes:
      - D:\docker\kafka_cluster\node1:/bitnami/kafka
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_LISTENERS=BROKER://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka1:9092,EXTERNAL://192.168.1.30:39092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=2
      - KAFKA_KRAFT_CLUSTER_ID=zt8eKmYSTnO4oWv8C0eDcA # 重要: 替换为您生成的集群ID
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_FORMAT_STORAGE=yes
    networks:
      - kafka-net
    restart: unless-stopped

  kafka2:
    image: bitnami/kafka:3.7.0
    container_name: kafka2
    hostname: kafka2
    ports:
      - "39093:29092" # External client port for kafka2
    volumes:
      - D:\docker\kafka_cluster\node2:/bitnami/kafka
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_LISTENERS=BROKER://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka2:9092,EXTERNAL://192.168.1.30:39093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=2
      - KAFKA_KRAFT_CLUSTER_ID=zt8eKmYSTnO4oWv8C0eDcA # 重要: 替换为您生成的集群ID
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_FORMAT_STORAGE=yes
    networks:
      - kafka-net
    depends_on:
      - kafka1
    restart: unless-stopped

  kafka3:
    image: bitnami/kafka:3.7.0
    container_name: kafka3
    hostname: kafka3
    ports:
      - "39094:29092" # External client port for kafka3
    volumes:
      - D:\docker\kafka_cluster\node3:/bitnami/kafka
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      - KAFKA_CFG_LISTENERS=BROKER://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka3:9092,EXTERNAL://192.168.1.30:39094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=2
      - KAFKA_KRAFT_CLUSTER_ID=zt8eKmYSTnO4oWv8C0eDcA # 重要: 替换为您生成的集群ID
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_FORMAT_STORAGE=yes
    networks:
      - kafka-net
    depends_on:
      - kafka1
      - kafka2
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2 # 使用一个特定版本以保证稳定性
    container_name: kafka-ui
    ports:
      - "38080:8080" # Kafka UI 对外端口
    environment:
      - KAFKA_CLUSTERS_0_NAME=Local KRaft Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092,kafka2:9092,kafka3:9092
      - KAFKA_CLUSTERS_0_KAFKAVERSION=3.7.0
      # - DYNAMIC_CONFIG_ENABLED=true # 如果您想通过UI管理配置，可以取消注释此行
    networks:
      - kafka-net
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: unless-stopped
