spring:
  profiles:
    active: dev
    include: iot
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092
    listener:
      missing-topics-fatal: true
    auto-startup: true

goodsop:
  iot:
    enabled: true
  file:
    storage:
      path: storage/files
      base-url: http://localhost:8080/files
      server-host: localhost
      server-port: 8080
      context-path: /api
      default-encryption-type: AES-256
      default-compression-type: GZIP
    processing:
      enable-decrypt: true
      enable-decompress: true
      encryption-key: your-base64-encoded-key
      max-file-size: 104857600  # 100MB 